### ISSUE TITLE
organizzare un viaggio

### ISSUE THREAD

**Issue by nicolaaggeri** [geeuleeo/BitWizard#5]

**Comment by geeuleeo** [comment]
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista Viaggi</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            padding: 20px;
            background-color: #f4f4f4;
        }
        h1 {
            color: #333;
        }
        .trip {
            background-color: #fff;
            border: 1px solid #ddd;
            padding: 10px;
            margin: 10px 0;
            border-radius: 5px;
        }
    </style>
</head>
<body>

<h1>Lista dei Viaggi</h1>
<div id="trip-list"></div>

<script>
    // Function to fetch trips from the server
    async function fetchTrips() {
        try {
            const response = await fetch('api/viaggi/lista');
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            const trips = await response.json();
            displayTrips(trips);
        } catch (error) {
            console.error('There was a problem with the fetch
operation:', error);
        }
    }

    // Function to display trips on the page
    function displayTrips(trips) {
        const tripList = document.getElementById('trip-list');
        tripList.innerHTML = ''; // Clear previous content

        trips.forEach(trip => {
            const tripDiv = document.createElement('div');
            tripDiv.className = 'trip';

            // Set up the click event to redirect to the desired URL
            tripDiv.onclick = () => {
                window.location.href =
`/paginaViaggio/viaggio?viaggioId=${trip.viaggioId}`;
            };

            tripDiv.innerHTML = `<strong>ID:</strong>
${trip.viaggioId} <br> <strong>Nome:</strong> ${trip.nome}`;
            tripList.appendChild(tripDiv);
        });
    }

    // Fetch trips when the page loads
    window.onload = fetchTrips;

    // Fetch trips when the page loads
    window.onload = fetchTrips;
</script>

</body>
</html>

//////////////////////////////////

@GetMapping("lista")
public String getAllViaggi(HttpSession session) {


    Utente utente = (Utente) session.getAttribute("utenteLoggato");
    if (utente == null) {
        return "redirect:/login";

    }
    return "listaViaggi";
}


/////////////////////////////////





Giulio Vacca
Fintech Software Developer 23-25
Matricola 494


Il giorno mar 15 ott 2024 alle ore 09:01 nicolaaggeri <
***@***.***> ha scritto:

**Comment by geeuleeo** [comment]
@GetMapping("lista")
public ResponseEntity<?> getViaggi() {


    try{

        List<Viaggio> allViaggi = viaggioService.getAllViaggi();

        if (allViaggi.isEmpty()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body("lista non trovata");
        }

        return ResponseEntity.ok(allViaggi);
    }
    catch (Exception e) {

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body("Errore interno: " + e.getMessage());
    }



}

Giulio Vacca
Fintech Software Developer 23-25
Matricola 494


Il giorno mar 15 ott 2024 alle ore 15:39 Giulio Vacca <
***@***.***> ha scritto:
